---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  # - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-problem-detector/ks.yaml
  - ./reloader/ks.yaml
  - ./smarter-device-manager/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./spegel/ks.yaml
  # - ./system-upgrade-controller/ks.yaml
  - ./volsync/ks.yaml
