---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.14.3@sha256:de15cf83364802318dfaf832fb008bde7e9c227dc877c9d03e81c7d0b1c20992
            env:
              UN_INTERVAL: 1m
              UN_WEBSERVER_METRICS: true
              UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local:8989
              UN_SONARR_0_PATHS_0: /media/downloads/torrents/complete/sonarr
              UN_RADARR_0_URL: http://radarr.media.svc.cluster.local:7878
              UN_RADARR_0_PATHS_0: /media/downloads/torrents/complete/radarr
            envFrom:
              - secretRef:
                  name: unpackerr-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65536
    persistence:
      media:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path: /volume1/media
    service:
      main:
        ports:
          http:
            port: 5656
    serviceMonitor:
      main:
        enabled: true
