---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
  labels:
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 100Gi
