---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: overseerr-rdst
  resources:
    requests:
      storage: 2Gi
  storageClassName: ${CLUSTER_STORAGE_BLOCK}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: overseerr-rdst
spec:
  trigger:
    manual: restore-once
  restic:
    repository: overseerr-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: ${CLUSTER_STORAGE_BLOCK}
    volumeSnapshotClassName: ${CLUSTER_SNAPSHOT_BLOCK}
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 8Gi
    # cacheStorageClassName: ${CLUSTER_STORAGE_HOSTPATH}
    cacheStorageClassName: ${CLUSTER_STORAGE_BLOCK}
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    capacity: 2Gi # must match the PersistentVolumeClaim `.resources.requests.storage` size above
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: overseerr-rsrc
spec:
  sourcePVC: overseerr
  trigger:
    schedule: "15 */8 * * *"
  restic:
    pruneIntervalDays: 10
    repository: overseerr-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: ${CLUSTER_STORAGE_BLOCK}
    volumeSnapshotClassName: ${CLUSTER_SNAPSHOT_BLOCK}
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 8Gi
    # cacheStorageClassName: ${CLUSTER_STORAGE_HOSTPATH}
    cacheStorageClassName: ${CLUSTER_STORAGE_BLOCK}
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 10
      within: 3d
