---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - eno4.4000
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  serviceSelector:
    matchExpressions:
      - key: io.cilium/lb-ipam-layer2
        operator: Exists
