---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-int-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - eno3.6
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  serviceSelector:
    matchExpressions:
      - key: io.cilium/lb-int-ipam-layer2
        operator: Exists
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-ext-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - eno4.4000
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  serviceSelector:
    matchExpressions:
      - key: io.cilium/lb-ext-ipam-layer2
        operator: Exists
