# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
    namespace: networking
type: Opaque
stringData:
    SMTP_SERVER: ENC[AES256_GCM,data:0Kn4MsBgu9TP6TH2QME=,iv:P3lggeVuquziOrghSya4qdpV3e4wtG58VGuFYnXYj6A=,tag:H8OH3sOaLqORdmNrnIkB9w==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:RRQLcGpJN7CvtnYTuqDRGo6FECTM5LclXA==,iv:u+xyGJeF3nZZOjkpS7uyfn/S/+FjeALiq8X+oPGl1Nc=,tag:R7JCNeDJDMBaK6L3ToFVwQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZJkha/Eqm6Z4lJAndrLWYA==,iv:UhPwSLc8ZS6ZMa9itTD4AJQ9zZ4ujkW5LVajiabScZc=,tag:d6z5AhODUlymC4rIJOheXQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:sxub,iv:cBOwhT5xEFmB093iUQvGWtFwdVGiGvJNVtjYmlpLvsM=,tag:naj41i7PVDRfj9npJGcziQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbVFCdXRYMStlR3N2RDU5
            T3BPN1ZXamFMSytGRkU2eUFMUWhXUy83VGhnCkRyd3ZBR1hWUHdyVHZJaUVObUd3
            b3pMMTFXaWRPS2g0bktxTGdOQXk1Y28KLS0tIFd3dDBBY05sd0JrQTQ1U29WdU85
            UE1FUFAwRGVvRVV1bG9RaXBhS2NMekEKeJQWMug5uhrsRqS6NyZw0T91Ny7srwV0
            lsxkAgzLBFr7QZ4cP0upVz3qhBbL8flYHDpI/EG5RuE3eZYVP1cWlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T15:29:04Z"
    mac: ENC[AES256_GCM,data:BIKJNm7Igj41YaqM39q+/nneUe5PCpwy0ucIOZXtup+aHpgzcWLG7f5lSSzMruBj8fQER9vwTuD5DuFL99ircNP9kpace+w9auRKcXmdfjasStzfSlWKXmUz5jmKVUk7FjKOte2Zuq36nBtAttONNB35BoE1E2RIarLWP0vWQdE=,iv:hggqdsJYs9S/mgy9y2hB1NQRwVN6gbnj2S50TYOQixQ=,tag:9ZEiOw+9+afcLSguAfV+Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
