# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
    namespace: networking
type: Opaque
stringData:
    SMTP_SERVER: ENC[AES256_GCM,data:hY132iGGYdB7CGJruZM=,iv:BVxIuOVZ5O3bRwHZhbVKEri+1Ri2v5dphpwtguxpgZo=,tag:l8rj21L0+MbS829pPymHQA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:vF3TSuDfdRSEHliJpGD6HvOW9yU2yP4LdQ==,iv:kRnGlnIM3DJwMZQHzSDv9nD8WHesZKBREMUb4mfPyTg=,tag:SMu8ILRlMsGdaZ7O9c/fvg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:fDNdUfLzQIWggh4Y7/vRBeRY4gzgD91+Vg==,iv:VkMb3XMS2m3VJ6U9CY8Q2FQEZDknsvaTGUN4YeCHzsA=,tag:VEtPxQ6D4iQsWf+1KWDPEw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:n/s0,iv:i/SSULjdeIYH8U1W4Ov1ytbI7YBPsscjI5Bttqypw+Y=,tag:6yEKJHwhUIfEdAwaeSgX8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQek5qS2dQSVhWcktEdU9z
            d0FQUDRnYnZDc3ZLVkRVbU5YZkZ6bGd6VmxjCkJ0RjQ2QklaMWJXVjg3TlFNbjJL
            NC9BZVlvRUtNZ3VOdHZjNXQxOVcyelkKLS0tIEV1NXExa1BzRU5McExWNC9TcU1L
            ci8rajlVa0FFbWkyZlAyTVpSYlBORmsK7mDGtPN8Dw+X3OfjuJeXG0kfYHaAM+0O
            IZi6dy4RgHxQB1X1vTk3k1UV/MPmPbM9ImyjufD//AC55JXjA5OQoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T14:54:50Z"
    mac: ENC[AES256_GCM,data:w2tcF63su4Z0vDdGfVCMlppggsOUJuuz5oH7UqumYrmvFJ0MWetkPETV5DuDufKO0Qstz7gqIWE3zfyo2C1FfQGiM/1tzcTxqtDjPHUb94i5zuH5ocHEo2Hyglzm2bHJNGUzgq6N6GX2QJo6xAwwGbNYxrmAkFgIvPT7lj4Iefo=,iv:ngchwgjqc3UCpBHI3A5uT0tEuWzQ6ENywZ1cQgKXpkc=,tag:wqLQy9W1G62gAyVlYo+gWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
