# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:IXsZE+4Jag==,iv:6gGtmadFrdlR8h1/vhwbPy2GLRgeffZSFpKg4gp142k=,tag:OYX/Kj8cfgZcS5+EutuW5Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:WOM33YFjoB9cx0zR7VuDX962NHWGu9c6jsSk1S4IIaZyfl1Gn6l8,iv:93QsS4b/vHs7Z0HabYYj+o8oTcuXd/fGjql0YDlk4Ro=,tag:PUbQi09Iq0gQ6BLys9+lww==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:PfeokUf5Og==,iv:1wtGvOPwZKNlGnwTNSS+5F7VpqX4I6apEomqbYNF/8Q=,tag:vZvH/5TEJ+FqKSrA2DB8gQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TRcW2XpO4A==,iv:f+/qeiNh+JgSlEZCzt2i8YCTVnNYz4wZe9qnPFIh4ZQ=,tag:JJZYBTnqdXUXUV2L5UG3iA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:v5EFQGuWVko=,iv:0lhAY12M7imrdiMjN04RmH/dOucPQ2dn2HZ6G52gp+w=,tag:dUMn2Ccenshys0npioDsdA==,type:str]
    GATUS_DISCORD_WEBHOOK: ENC[AES256_GCM,data:/XYMM6RqAlfwb4q48q5ommrZw5hfrRqwOJfW+tr5zAr5V40wNg6N+cXgSmTkqKui8bjCwUvd+Ry/B3aQtYwLAJWQQEhHcvwONkUiyKWw1Kv8ho7EuHe0AudkpO1kKGOZypFZsr6OunQuyd/9M1WFz03+e5ReyE+RoQ==,iv:u2JXhFPZRSKwrp3YajTgBOr5SqBz2z89nyocT0ird0c=,tag:XQIqwdSwDlpK5zbl3nf0/Q==,type:str]
    #ENC[AES256_GCM,data:Ab7MModm1STi,iv:qrMvDRUn2IFAs7XiLaFs8TExWYIN8073f9RczXr7U/I=,tag:RTw9leH93n2woxVvtOMHPw==,type:comment]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QLLiEVq6u335p+M=,iv:Dz2h+PVS409MtQEUI4vmoA936NoW5xYe4tqz1W3bObs=,tag:LKn3FdiS/tF2joVQdyZX0g==,type:str]
    #ENC[AES256_GCM,data:SE8WL9bZ76A=,iv:IXQnAxkG185QJxlQrToQXMqfjOWCRUETS1a5Ru+60vk=,tag:U9aE5E+6Lert3kTH/AD32g==,type:comment]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:CZVxjkC40w==,iv:s8YWpfUMhRW59fk2rC6HSN7S4nJMXqzUDmirviYwGdk=,tag:FPpPojfh9EqAU5NY1+LGFQ==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:lTnIUKmUGt714g5NMZyh1lPn8o7ud5/bSxZqn+vE9mK/mBNiCNgW2luIPYoj,iv:StEYa4qQme3AYEaskYasMNq+Wipiwp/j7M9x7XELJ8Y=,tag:vIqCfFHdeL9IJf9sVsBhvA==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:Sv2KBYML+A==,iv:fmFfz0/CLFCuH6zHVJlEd46IiltVsFHwZTzg990APGw=,tag:YF/LTyU8ChgpVF9t3j5Tyg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:mZ40jytkFQ==,iv:FEJ94o2NW3R48RkudwBmFvsLE9SpFvyZd4hZFTApLYw=,tag:jYNIm4RZFlrCMLNo3yDHnw==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:2Y4qTO+hrA==,iv:GRUnMxd3HzlSn6m/SP9LbvKBj2Ulemx1DrpAUrrh5rc=,tag:H0u4HpQb4jlHRKdF78Dy3Q==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:BK2tgBZE2ic=,iv:fEcfhbbZQAQ7+q/KGzNIAdEwNGmSlcd/0E/T7oSNF1g=,tag:3oyksObx+GY6Q/d8mZBr/A==,type:str]
    #ENC[AES256_GCM,data:9Wvhp3D0d1wRbU/b+Dc=,iv:EhFvcVBiA4209coAwyu63Kua8w8Os8xCZv8G9Jb1VRk=,tag:j+CKQzBUonX9I/B4wyG/pg==,type:comment]
    admin-user: ENC[AES256_GCM,data:VNbVrTU=,iv:7WWGEWjSQIs5rHm4TxSAcCPw1mXhh0OqIPgnwx4y514=,tag:25pvxx2CciG+rlJC7NRY0g==,type:str]
    admin-password: ENC[AES256_GCM,data:7U+QRiE=,iv:1C3gpF8HgIUSgXvyR+VZFv9Y7Y04r5R1BDL9mKl2lA0=,tag:sZ1K/VHqsUjrk64vaucttg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobUo0UzhRUkhaSmxOU2RD
            SWdSQ2xFbGpqNE5LWHAvMkpCMm56aGpXdTBVCjk5Z3prY0RsbDBGeC9tN0VReVFC
            dEhaQm5ZSlpCTThENmJyald4NENVR1kKLS0tIGdKc1Z1OXR4Zm9sRWdKaUpLU1B4
            MDI1cDVVQ0lEVFl1TFlDdjNtUTZPdW8K7QFQPvqq9B3QrGpZX7IW04BKmbl4l9pt
            eMUq/oRBPmpkpmcQK6BAeK2GEo84MjYsmOJb/c/OmtlSQACJkW8v0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T18:29:43Z"
    mac: ENC[AES256_GCM,data:sMuCM85FqgrLQwIXkhLz3AllJF3P3PWPphdWKxjDjm5Lz/LXMQgxj2ha7yx0V5HFkXY4fuMoEdENBwt5QBnpLwrEOkUpA36h7Ac1faJsGueBFjHfwgDVz58DKEa5kMNAHy6Yjy0c2SuzGp0NkbhpZYfDXhnnr4rmchMQcDbQtyk=,iv:aFTEh7f332WO47PRtDuhStLDZncJ8wXZwVYzavnBNns=,tag:zUjl6taRw5b5FTxE++JX3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
