---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.11.0@sha256:6e04812ee4a35fa058eb8019b2b5f0f4aed254e95c04ca152cb03a25c8251edb
            env:
              TZ: ${TIMEZONE}
              UP_UNIFI_DEFAULT_ROLE: k8s-gitops
              UP_UNIFI_DEFAULT_URL: https://unifi.${SECRET_DOMAIN}.
              UP_UNIFI_DEFAULT_VERIFY_SSL: false
              UP_UNIFI_DEFAULT_USER: unifipoller
              UP_UNIFI_DEFAULT_PASS: 1nternalUseOnly
              UP_INFLUXDB_DISABLE: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
    service:
      main:
        ports:
          http:
            port: 9130
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
