---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: homelab
spec:
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local.:9115
  targets:
    staticConfig:
      static:
        - unifi.${SECRET_DOMAIN}
        - nas.${SECRET_DOMAIN}
        - ups.${SECRET_DOMAIN}
        - pdu.${SECRET_DOMAIN}
