# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: authelia-secret
    namespace: security
stringData:
    #ENC[AES256_GCM,data:QYzCdxirAp8b,iv:+oalrgUS4YwNohcrKyfsq+wNa2g925JCeZwWeZ7lXV8=,tag:+Wb9eHsvPULIK4k8e6+uoA==,type:comment]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:HXJTuMkbTDH/esWtsqhlNwDNehzujwUF22c9bfGi1Obb7Bro74Cxl1MylnPWhzyf3FpIMw==,iv:qMoDu+toTPIIQMzttntljrONQT9CUUnpC3hwZWNxKio=,tag:lAN4YXcRycozbWhWRjNEhg==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:WCwBNZkr0I9keiuA2ACWC32KvGrpNReJGwuOeGCfTpbwAp8aO/S4TwacB80B2MUt2zCZ,iv:m9xqOibqxTAZcZ018TEHxbUWTU76IM8CjFgaV/cBcnE=,tag:6ZBFfEOwBEkn2hdW6SK3Kw==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:Sd3N7mchhIzIHMGs11knoNgObC+5Sg44JCZlPD0K3V8aW7dZfmPrMQWeehQR0n6Drumi1buKVmC6/Q==,iv:DD7l2Dohx9WrhRQn0jQFH3Nr/NUmPXoaHIXZKNsZ+Tk=,tag:3+mnUE7xqq0lrpKd4dl0uw==,type:str]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:2CNSlHeqVUrF9OBkCTptJFiHmAm9lGXx/HQ=,iv:G+8eNjRj7T8Q0i8OF0SjguslaNE/l9HYPWzCITCEgoE=,tag:PIRo1hlFBD6Wqml4xljjAQ==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:+DTC3gdS2Ju9udAMdHVtCcY590KRA8Ot7ME0VMAv,iv:eqJEVHSMkHelo/+IXYuY1vHGao3skxe8xH8hAbIu0mU=,tag:hVEWKL2bvhEFU4p3ixD+mQ==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:cXxA2+N78ai8zW5JF5Pj0zRKlhEhJCKlp2gxs4Z3XSr5ypDyfd8=,iv:tT5kYGoqk0aQo36oJFXiwx/egJEfdWqszGKqLYQYhN4=,tag:Cvauqxrrb6sp+/idqECN4Q==,type:str]
    AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:Ak5l3Z/PYzo=,iv:dQQinJESG406tyezl+C6rUKEsLtKJ0oNSLZ024Id7Dc=,tag:MFfx9ZbLlbTXqvKj33XtXQ==,type:str]
    AUTHELIA_STORAGE_POSTGRES_ADDRESS: ENC[AES256_GCM,data:9Fa9883igZwb6jbFUAmrCciCDTnxKoiLvkHsEb90bqLqGaQgM8IF,iv:b43cJptaOVD/E+P3iR5Ff6FjW/tnrT+N+f6pvzbOpGU=,tag:2vZTMI8IgSI0GbSu0HqukA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:kLPxucx6Jqs=,iv:mKxeWQINxKQzRgn9AkcYEiIMWCat6zwXjJiERWgNfXU=,tag:oWDI1O8BGKgnbCy/3OxZWw==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:6UWrdgWvz08=,iv:eKGx/vw8MG/vOrwWJDy47KeUP4+oDX2IGJ321/FwzPY=,tag:L5tfKj6mnO+xCCxFOtk+wQ==,type:str]
    #ENC[AES256_GCM,data:72xxmsz9W2tPCA==,iv:kPjLvZ6d/xXIXcUyyvIUA+ii36BQAb9RpdgeHtrXSM0=,tag:VX/qwcoYizO7mVVCbnJZeA==,type:comment]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:UaGAK2fPdF7M60st529x2JajD0knyzKbGDrWpUL/FkCcJw==,iv:EhIXbeA3yWjn8LpLUEydEQeQ6oZ9qRA6BNWPQnvmqQ4=,tag:yKZzzQSiOjecWOZ8q0X8DA==,type:str]
    MINIFLUX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ftasQpf3Z+ZwEClKYhV1wtm/pDD583EbfYg+dTJ3VmbPHJg=,iv:igaI4q2TMEW8Lso3kZFUzjN4Zu2Ylx7hAbn6rcGGsL4=,tag:mA3MrBhzZyk2DEz/j1DvaQ==,type:str]
    NODE_RED_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:K0e7ycccb6EQol+9Gq3WLv5+5PiVXW0Coh39JKnvtNipacM=,iv:wT+//1PUsrhHOPODzP8wKa8bFjMUkxbUEQ867qJYgHU=,tag:gZvk/JkSFeLpuwEiqVNgvA==,type:str]
    WEAVE_GITOPS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TCSQtQy0WNccRsgIuP7wLU7JP4PG7nEek/UKTP44FDbMnVY95KjG,iv:Ed3k8e1jhyrQF/op8WkcNb8NCi7xbAYcLHlhiN8mZXU=,tag:Af8lm7vqq6OGqbgVZ9hbSQ==,type:str]
    #ENC[AES256_GCM,data:39FuyrMT17Z+jcd0zEI=,iv:FKdm6YaNWn2VfaKE2tMeEjB+3bZgPsyTqy8tDF59jlo=,tag:G1/IorUNYhbmUsF51vPNsA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WaDG9EmkT7o=,iv:/3Qw0xwjVrGKykk56Yh9kgvqo4fuCGoyA8ns9FWLfq0=,tag:RQgx1ZachXYln+D/VLQKsg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:wiGmvtGaSZWtZAmZtOEAjHv9jhjPZEDxvdPZUUMbNme+ZA2VBUep,iv:1Y9AsllgjNhFW34pp+ixT3e76vIshCeNKc/V2wndj4o=,tag:xFawqI6pWvM4uSSoqGp3rA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:UmI89LWNoP8=,iv:r6dhWNCI6IbCQLuOTauKINGC1ik8auQho68lM8VF0pg=,tag:H7e1vc03Pr13VIPV8AqXAQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:We1j8l4koO0=,iv:NVQougyDUB0V9fhsBVxmU99laKB0IDC0lnMrl7dW0ow=,tag:DdW53DUSI6NKnQ9yG+V7xg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:O6q/4mlCnDA=,iv:f/rwI07Mow397J5DsM6v6ZZSbLk6JEm6/N/DEbHUK3g=,tag:en5/RsbUoPiVQ0/NgtjhOQ==,type:str]
    #ENC[AES256_GCM,data:ep2eDio=,iv:G2/ukn/fsIZy/M15TTgC32LTUkZ6rlFsxhHf2xEbU6c=,tag:rNbIMz3AD7Rt9yiw1xixlQ==,type:comment]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:r0iK4r49rT+5Q6mbtM0KDw==,iv:pZQXCWPzUVS+K19sLwWb3VnPb1Dm2FgFaw7cHxGNFv4=,tag:PPi745rmJwd4VhjBTRfvcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaEw4NE9zcjdIRm1hV2dU
            OWZkZTFQb0NqY3RpaWNmSzd2YWM2aWdMNkg4CitiRGFubXZaZC9PeTY5Y283VnAr
            ZC9HOUNud1R5TFgrckNyZndnZk9WeE0KLS0tIFRFZ1Q0ZUJyTkRrRTNnV29RYWgw
            YnR3Ty9mL3cyUDJ2UHlhbGlobmVKbGcKTdDjVgBLOWPET3suzGWAem3osaDn2jaY
            2DkKzY+Z8/397KLNryk9ZOd76UcbDCwRdcV9L5fhd2ZcJfR+85thzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T02:54:28Z"
    mac: ENC[AES256_GCM,data:+ds4DnhaSbPRDwJ0hxeccqGeH1PECWbPsA4o7w++IsI18v6dobr8GRNNVA8vXTP+8MzK/n2JsxwSXlVIdAYu+mv0PV+41QbH0ePMp3U/MwHsDbQ4ktAOWI2blP1RCC90kjRAK97OVGF5ZVNo+NHEkfn/GTlyxpHlNrClPJA2Uxk=,iv:L/aGWZLWNkxaacp25LybxQvnVj7fVSSKp2GTGzmp8HA=,tag:ACB8swlBS8gTuCUbk6RBzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
