---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          configmap.reloader.stakater.com/reload: &configMap cross-seed-configmap
          secret.reloader.stakater.com/reload: &secret cross-seed-secret
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3@sha256:025f32d260a3e924885405c0ca01ab8e396360330438ef8562ffd973d2dbb927
            env:
              TZ: ${TIMEZONE}
              QBITTORRENT__PORT: &httpPort 8080
              QBITTORRENT__BT_PORT: &btPort ${TORRENT_PUBLIC_PORT}
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: >-
                ${CLUSTER_POD_IP_CIDR},
                ${LAN_SERVER_IP_CIDR}
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_BitTorrent__Session__Interface: eth0
              QBT_BitTorrent__Session__InterfaceAddress:
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              QBT_BitTorrent__Session__InterfaceName: eth0
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          xseed:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 6.8.4@sha256:996896878ab462ded031552824c4fd773a2cf484582829029eda323b3c01e1b4
            args:
              - daemon
            env:
              PORT: &xseedPort 2468
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext: *securityContext
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - sabnzbd
                  topologyKey: kubernetes.io/hostname
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65536
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:seedling
          hajimari.io/url: https://qb.${SECRET_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths: &paths
              - path: /
                service:
                  name: main
                  port: http
          - host: &customHost qb.${SECRET_DOMAIN}
            paths: *paths
        tls:
          - hosts:
              - *host
              - *customHost
    persistence:
      config:
        enabled: true
        existingClaim: *app
      media:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path: /volume1/media
      xseed:
        type: configMap
        name: *configMap
        globalMounts:
          - path: /config/config.js
            subPath: config.js
            readOnly: true
    service:
      main:
        ports:
          http:
            port: *httpPort
          xseed:
            port: *xseedPort
      bittorrent:
        controller: main
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${TORRENT_LB_IP}
        labels:
          io.cilium/lb-ipam-layer2: "true"
        ports:
          bittorrent-tcp:
            enabled: true
            port: *btPort
            protocol: TCP
