# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:3zmErqOes2PAtJyJilMfPZvJ0AFsWj9IRz7QSjfRXu+VllN+kw==,iv:GPmdayBB1KtfYXVH+BgwD1uz7fMQbtRG5OULDSuhyBk=,tag:djODCBE9ANpEDjvU9kkYmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UmlLNk4xaFdJUlVmaHhv
            ckVnOU9KNEwwejUzbEFOU1RhSjdBZUZlajEwCjlmR1d0QlFiYVQyc2R0R3N3Qm1G
            VzhrdWgvSys4VDU3OUllSVpjVUtNTDQKLS0tIFV4dmFHR2xLYU5RUmRrTWFFdVRD
            bk83YWFNOGlvbTl4VEVnUGlTTFIzZ1UKSAanmi0FJ6DNZFk1mcTfjMs+t5+2Cv7F
            iOL9XQpZemFhbm2da0wXgz4lPp1flH7LMz2P3FMCeJWKlPE8qVMoWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T04:08:03Z"
    mac: ENC[AES256_GCM,data:QDC7ytK+NOCcllDDlNLZ2AfBh8Aa3YuQjTE5jSXVQpD+VU8332Ee/EavWRAELigLdzAjuYOv2Bh4Qh09UEw4aGiaS6lLerwwJCWAW1kwL0XrZI2RqNVhvt8lggo6rcM1bnoulxP+iHCSASlBiv230/mBpbWOAYNDFfv9omzGwiE=,iv:RR06zKAsJRCuQ14PzpTOzFlztW9BfyZ37SU/69oiHoI=,tag:Uxu2phKq6Q/cNPmt0XUeLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
