# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:o6XwHd3VSBgbFEBFwCsrDrSYUPFm7JMA0qaiB7hGzJ0thW8WRREyyg==,iv:eoSZFDPkku1yyEOG4PyuH+VzUN9jNaPrpYxfBVjzsl0=,tag:2gegLSxzHkejumn1SlJHsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL2RHWDBpWnRHQTFEcWRP
            K29sT0ZLOU1ITFhkM1lkcjc2a3JuNU0zUmkwCmhYOWpTcFE1YmJnVXpWNmora1Rp
            K1F1Qmxvb0ErZzMwUkl5alNpVnNCc2MKLS0tIDVFSkZlZ3NDSnBET3A3K2RHQmhi
            NCtCU1Q1MkNBWElCWkx5eFhvb1hTeWMKpAUp23kZ4ZVCuKoOb+akFCh72U+REU0F
            uy2D9G7mk/XheonGXYObI7I60AG8WSqUVAWBuDMGNBn6F2t6GwHrkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T04:28:20Z"
    mac: ENC[AES256_GCM,data:bVGZtbHw1Wue/0VfIqqz+k38HGMs6WTIGJdL/ROAfj8sp2qWW8tRmlnODajh0ln4Hx103m5qZ3c/owagwlBnBzQRlwDNVUNz29gmtx3dXSv/IetScxC44pyE1bogSVoMdkcazntgV0aJe56YALyhEX67egrJHZWHFQtLgNoSjDY=,iv:M07SgbQaRwoNigjPUduMP9RoLIJy5SsHsninJ7TN4go=,tag:0S0yBITuBdGOyfU+ifAQ3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
