# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:4UKSLd3OyT58EAF0vcdOxrNbih9Vti44FlCuJkahU4lP4W4p1A==,iv:650CyEcbCmEwL20ZLdRB+epzPE7FhJzNrwTymS+w1Fo=,tag:l45rE7bcw0OVaLLOLUiAXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeDlGckRMNkpKU3FXTDNw
            cmZWejlPTEJ4L2NkYStwb25Ca000MFAxem5JClZiWXdTVk9aWFVWcDVFZ1RaZWM1
            S3JGYzRZSU9kRlFOUjZQcjVCcVlsNncKLS0tIEFuZCswaVBVbW5KYWx4cGZWem4x
            eVVZYmh2U21waTN1MkNoQlZGOE9BK28KVtinsnTwJmw4Iq1VtVA59cZW+9oiVhQW
            AwLMlIFQcHNi9YJlsSj3ItnQzuFMq35SJ7fMmcM2Xe6UbxfyjDBsMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T19:14:36Z"
    mac: ENC[AES256_GCM,data:W9DbfpGTf45lAfaSxI8TqSd2xPc93tptCzWoRYWvKCrLNRXIYWf7K0JLhPe4upwqjIhsFTmYuVMLS5f8/RrfVFmsOOkN1YRlXL8FIn0ia6S+hC9oSt42s9F0U8LXgWNiyUjdRm6U66rw6KdNEGyLXyee/6uJFp/LhfcmFriTNb4=,iv:/rVZUo8oIQozlrZDhYcOrtpLTFtP9msHln9eS5TWUYA=,tag:A/rREGgPZERwXUm4YRnbOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
