# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:1xNxk4YPbGclXH2IKhC8y0UL6+MgN7ygKItOd3BA6UqGsi12yrH+Cg==,iv:C504kIf+Eocr2mztZGm4U+bsjnxTZgGXpj3vErdz9yc=,tag:XR5tbp32uavDZsWVeDIwaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWk42eDBTZnIzRHE1SHAw
            ek50VDloS0QwUjREWDZRSmI5Y3VUTWNsTGlrCmdtVmpIejZrdXhjMmVYaXNoYytv
            WUNpcU04SWdnTVVUQUNiRGVGODNZSDQKLS0tIGlSVXN3ZENJdWoxbEJ4Q1ZqVTZv
            Y3FHZzFEbEJGZmUweEZxQy90R2FtcWsKpl/uPt7HgHn11HwSqjGbqYo8gFjvJr8P
            XA4wsN2+Z3A4WyaQfNjQ+tqe16bJZ3Lsz7xlczqilwNDasrv3L48tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T04:31:32Z"
    mac: ENC[AES256_GCM,data:r2AZ09vTiEhEA3QUChFUKQK5AaAVXqDOqCwXa5pJ/Ey4HVbH8bfLrfZqJfC5QRdVJgVmpY+i/HKD0A3vimC9lvQXQxVJx0lJqQwKlVeY6c1ih+bMuYebXDyEWtWtlnjuvCnzkzcDy/qezpvH2BASqwfx7wD2aC1DHMRYH0ELwXU=,iv:bAyyFK0hktB7FoZ2xKboK6lkQwMKtWYO78Sd3AxXYl0=,tag:oMQn+u8Ll9lqD/ixCDpZlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
