# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:uAr81T7v2bwyC8lizXY23Ob5anamwxc5MKhCPuBp8nbxcdRFzIwE2w==,iv:ne3M7Wd+WBWeF3pmYt31PAIvyQcl7jMxdfpyQxqL034=,tag:gIdeKBUkRrsf6+f5xKaKzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUGRER1VJRmwweU8zOHNZ
            NEIxSVpXb2tUWTNkdksrUmdnRThrK2dQdFFzClN6WnBKNjBFOE5vN0lNeHYya1Zj
            RFNySTd5WXNDZHA2ckRNakUvUkhFcWsKLS0tIGhnTzBUOWt1elVETjhEZlhaMGtV
            OFRMeHl2cnp4ZjhiOUhpK1hqSjhaKzAKLlghliZ4JEEYRY7KoO96v1LccIafRXen
            xqUq5j/HAdb9Ya/iIPUtaqW1hJINMZ3sw1mU18OutRSJazWFGU7K1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T04:23:59Z"
    mac: ENC[AES256_GCM,data:EL4Tt5AWfC1SH4cMex/9O8mVxa0WW/OaJyd4+74uJXgZrxzH0g7wirQQBtOZp9N4TwRhVXjeE7F8Qj2An9WbWpFiKv37hHyhj7zve8IWSZNPJFDJqGjBBp17uKWXNl0OJdSzDYVAq2qGnPE0AH1p1QTAognXTp6p4+63PzGLpPM=,iv:uyvOo8ImoHxkELMe1WTPMzvpwcQGcMrlDPfPuj4EMSo=,tag:xHhJTxIsPvZ4A0GJk09PPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
