---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.14.1@sha256:7bb4c52748dec4fa2df1a8df7b94355c9677c70378cfe555ee4eb9a476409f0c
            args:
              - --cloudflare-proxied
              - --zone-id-filter=${SECRET_CF_ZONE_ID}
              - --annotation-filter=external-dns.alpha.kubernetes.io/target
              - --ingress-class=external
              - --interval=1m
              - --log-format=text
              - --log-level=info
              - --metrics-address=:7979
              - --policy=sync
              - --provider=cloudflare
              - --registry=txt
              - --source=ingress
              - --txt-owner-id=k8s
              - --txt-prefix=k8s.
            env:
              - name: CF_API_TOKEN
                value: ${SECRET_EXTERNAL_DNS_CLOUDFLARE_API_KEY}
              # - name: CF_API_EMAIL
              #   value: ${SECRET_CLOUDFLARE_EMAIL}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7979
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
    service:
      main:
        ports:
          http:
            port: *port
    serviceAccount:
      create: true
      name: *app
    serviceMonitor:
      main:
        enabled: true
