---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vector-aggregator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-geoip:
            image:
              repository: ghcr.io/maxmind/geoipupdate
              tag: v7.0.1@sha256:80c57598a9ff552953e499cefc589cfe7b563d64262742ea42f2014251b557b0
            env:
              GEOIPUPDATE_EDITION_IDS: GeoLite2-City
              GEOIPUPDATE_FREQUENCY: 0
              GEOIPUPDATE_VERBOSE: true
            envFrom:
              - secretRef:
                  name: vector-aggregator-maxmind-secret
        containers:
          main:
            image:
              repository: docker.io/timberio/vector
              tag: 0.41.1-debian@sha256:87ef5d0a3f47ed6e415c9c6b84f7bfa53dbced55c00b75a974426a8a63cebc15
            args:
              - --config
              - /etc/vector/vector.yaml
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    persistence:
      config:
        enabled: true
        type: configMap
        name: vector-aggregator-configmap
        globalMounts:
          - path: /etc/vector/vector.yaml
            subPath: vector.yaml
            readOnly: true
      data:
        type: emptyDir
        globalMounts:
          - path: /vector-data-dir
      geoip:
        type: emptyDir
        globalMounts:
          - path: /usr/share/GeoIP
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${VECTOR_LB_IP}
          external-dns.alpha.kubernetes.io/hostname: vector.${SECRET_DOMAIN}
        labels:
          io.cilium/lb-ipam-layer2: "true"
        ports:
          http:
            port: 8686
          kubernetes:
            enabled: true
            port: 6000
          taloskernel:
            enabled: true
            port: 6001
            protocol: UDP
          talosservice:
            enabled: true
            port: 6002
            protocol: UDP
          unifikernel:
            enabled: true
            port: 6003
            protocol: UDP
    serviceAccount:
      create: true
      name: *app
