# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bazarr-secret
    namespace: media
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:qA2A2Q==,iv:RxCAhoOtxTxDm0R0auZe7DwMkID9Ik5vkF8WYAvxW6c=,tag:9uxFaOI+PLrjN8hzB/1pEQ==,type:str]
    POSTGRES_ENABLED: ENC[AES256_GCM,data:Cw2dgQ==,iv:2wIRroe6+97aYvOjU7k9HobTjP5XfPYvI5GrfvnqY9E=,tag:Ro6MazSdHPcBeXDAyKfW0g==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:+y7jCstF,iv:C09LhNeoydIORW8lbIqzToku//Hgt7NpvT4iiYhswds=,tag:0MAvjj61/5EtRUIZUtXvyA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:hAsmqwZ1RxTJynNW1oFzUCJr2PhgznNcBPTIWM3SmBIIvc32EazV,iv:vfRoZU5B87oZbsvPlYhk2fB6dRFa5JUKxae7TnDHxgE=,tag:CHvBM1ufS0EdUGUoOkeNFA==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:gpEIww==,iv:jry1F69p/2gPEi6seI+3xF/gT7Bw+94QN/AemD0j5tk=,tag:O2KxEnFG0+aFOeR0mAiWvg==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:lheowPla,iv:GwadG9lc4T56yayMIY/AN68cDo0MReq3MZ1jpIzLEAA=,tag:IjxRe9BKii/m9Ws5+2zlEQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:F53+rut7,iv:vqNkHU+NFpdwQFm0H+2doEoAxZRCSIt6uS6axGxzY6A=,tag:TaKJrkBFOCCTij1ylEGjsA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:EhhqsWvT,iv:kyd87DItQH/Pgmoux3vLO0OlEvEtjjXDc8ijzajDo2w=,tag:DkTGQXao6M+qJfAAijq73w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:WuOqjHmkVxgZQy3IFK38KBKALqWkvSximY9HUx+qykqHe+H5bOT5,iv:Z9VQ7oS8DiyIESabCbsiquwy0dq6kOftdKoDBhtVAyM=,tag:5xTZ8qkF9eKlYhKTs7ypoA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:95HQ9tgE,iv:jjbpudl3rOj1GPGp6M650dKF9x61qkNoi0xX1+dAX88=,tag:paroH4EwkMzShJZ0LLiQMw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:tO7WtJBK,iv:k/Lvo78Hr3khxzE7k8dWqxDKzLfsquxU98RqWlWSFbA=,tag:tZMHBhjLHCAT2T5rYoexxg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:JI8zzrMXuJ8=,iv:BbX6o16cJpmEq3rh/sD0q2X7YAQ/hQ7AXsXx2SX5cwg=,tag:i3LM7HCyFHBY2jDt4Zri9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb1FkQkJadlF0azVWa3ZC
            dWdXdkZ0bWRTT0wveWxDcGFvSEZPR3dXOG1VCkFvcW8yQkk0QUc3TXB6aXlzTG5G
            emoxV2hRTjRVR1lJbGpJRlpoNkcxclUKLS0tIDN4ekxQN3A1WDluVzA2c1dhOHhR
            TVJpbjdmTWttcFRJTHVnWXlnRk83RDQKd9PBn+a51yhIA8IC500ogExQYj8KbsIB
            h0qGIDUEnBYvudZci0ms4xho6QA1ivZvAsoP+/riLkhyPhzy45V9ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T15:06:57Z"
    mac: ENC[AES256_GCM,data:oSi67bQJxBkqtps7301iJ4TKyCTHN9dm70OtK6UwLaWXx4Mx1sJu7OnKC35vEnNuXryS+L3jKpj9MJSAIUP9W5kHnei08wSQlSX+KtBJg2t1NwtLf/ZtxO3gz04fhqmFvM/Du8m9pBQbEaYwOcSed2MRvMPq3TEgR89NQAcxh7k=,iv:Khv+BubDYpXH7Am0hSPJUH1nexkJcsQ4ZXcq7kLpkTU=,tag:2D15s67P0GEqjQ5UErC4sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bazarr-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:qybLyfm8p1KBTRwc1cZvFVWZwFESnplbz6tCUSaLpQIuJoH6DuQ2SejrerxJ3r2aTJv19thRv02F0Fk9DCaLXwNnRkEuW/cKKvcSHCf3oJBOL50Ix4gMxypJ,iv:2FkeLKiV2AXmIWM1H4aG2reubToX01fVQuPTYbnHv8A=,tag:g1tT8rSZdg3fwCO/reUA5w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:I4IvaUHACr/oCUK+EA==,iv:gD6xT0Y6c3Kyq4U7u57svgTKaqczsipIqn8wmhJ8hUE=,tag:sRbEaTwpkGM2x8pb7/uuvg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cwPqIYRSnc8Ou0n3roTgUZcGc2x/3iD2R7gfXNSOa9E=,iv:uIiDHjgdlbQsEZ6ZnJhmI0pAjGmyFcRmNJBOEjvkrMg=,tag:UBZZx7LtsxZOccJVlUFJKg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hXx8KGyJKbKdn37NuE/bCWojFiZArD8YPvfNonakUVWbllpzNtXmuAPFu8jCNXQMlIomJKPzoCMb98LNcvB0kA==,iv:YwJkifKkYFkx0tIIzcsAzoFnRBVcNB5uVDHFlZ72n6M=,tag:n6h2rurb6pAFOvchnijYpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb1FkQkJadlF0azVWa3ZC
            dWdXdkZ0bWRTT0wveWxDcGFvSEZPR3dXOG1VCkFvcW8yQkk0QUc3TXB6aXlzTG5G
            emoxV2hRTjRVR1lJbGpJRlpoNkcxclUKLS0tIDN4ekxQN3A1WDluVzA2c1dhOHhR
            TVJpbjdmTWttcFRJTHVnWXlnRk83RDQKd9PBn+a51yhIA8IC500ogExQYj8KbsIB
            h0qGIDUEnBYvudZci0ms4xho6QA1ivZvAsoP+/riLkhyPhzy45V9ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T15:06:57Z"
    mac: ENC[AES256_GCM,data:oSi67bQJxBkqtps7301iJ4TKyCTHN9dm70OtK6UwLaWXx4Mx1sJu7OnKC35vEnNuXryS+L3jKpj9MJSAIUP9W5kHnei08wSQlSX+KtBJg2t1NwtLf/ZtxO3gz04fhqmFvM/Du8m9pBQbEaYwOcSed2MRvMPq3TEgR89NQAcxh7k=,iv:Khv+BubDYpXH7Am0hSPJUH1nexkJcsQ4ZXcq7kLpkTU=,tag:2D15s67P0GEqjQ5UErC4sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
