---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      createSecret: false
      username: admin
    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/icon: simple-icons:flux
      hosts:
        - host: &host gitops.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    # ingress:
    #   enabled: true
    #   className: external
    #   annotations:
    #     hajimari.io/icon: simple-icons:flux
    #     external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
    #   hosts:
    #     - host: &host gitops.${SECRET_DOMAIN}
    #       paths:
    #         - path: /
    #           pathType: Prefix
    #   tls:
    #     - hosts:
    #         - *host
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      # impersonationResourceNames: ["admin"]
      additionalRules:
        - apiGroups: ["infra.contrib.fluxcd.io"]
          resources: ["terraforms"]
          verbs: ["get", "list", "patch"]
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth,oidc-auth
