---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-red
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/nodered/node-red
              tag: 3.1.10@sha256:13b5783bf170e87df18d3b881750d2b00c0164163f89ad47d03f6fc4cbe5e2d9
            env:
              TZ: ${TIMEZONE}
              NODE_RED_OAUTH_ISSUER_URL: https://auth.${SECRET_DOMAIN}
              NODE_RED_OAUTH_AUTH_URL: https://auth.${SECRET_DOMAIN}/api/oidc/authorization
              NODE_RED_OAUTH_CALLBACK_URL: https://nr.${SECRET_DOMAIN}/auth/strategy/callback
              NODE_RED_OAUTH_TOKEN_URL: http://authelia.security.svc.cluster.local:9091/api/oidc/token
              NODE_RED_OAUTH_USER_URL: http://authelia.security.svc.cluster.local:9091/api/oidc/userinfo
            envFrom:
              - secretRef:
                  name: node-red-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: cib:node-red
          hajimari.io/url: https://nr.${SECRET_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths: &paths
              - path: /
                service:
                  name: main
                  port: http
          - host: &customHost nr.${SECRET_DOMAIN}
            paths: *paths
        tls:
          - hosts:
              - *host
              - *customHost
    persistence:
      data:
        existingClaim: *app
      settings:
        type: configMap
        name: node-red-configmap
        globalMounts:
          - path: /data/settings.js
            subPath: settings.js
            readOnly: true
      tmp:
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 1880
