apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: null
    #ENC[AES256_GCM,data:ZDibe5LdIw0=,iv:4OiN8TUkrAnwyaGA8wBLX8tH/oCQ1RuExl0toTuowQA=,tag:fQrKCB/j8sF65ZwSNjYCKw==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dnpHxX0/Y39T3bwTtg==,iv:To+7DuyM4mUd47Id5/RM0/rHh4DgitI+rEiAoje345g=,tag:CaZzJfo3jUrKFUM6Zg4Hww==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uRUkWRKX/+M10PtmKivGcMWOj7ex0Bsm4w==,iv:Gyh6EX9OjuVZsXxLoYdlUsEOftFIoRqIti9sCOhi0KM=,tag:1SPe/PgjAgugbWcWcB5YWQ==,type:str]
    #ENC[AES256_GCM,data:cGTDUs48+Q==,iv:zYD6YIO3YXwXqzUNOrJeCnhE8UBQsjqnsyRASwR8/lw=,tag:NDvxZVuwlOwbcO/C/eZn4w==,type:comment]
    SECRET_EXT_INGRESS_LB_IP: ENC[AES256_GCM,data:BYIVsEIGya5XPnhyViE=,iv:TQpcMb/WpFDQgIBGPja8udWdIyUiIzh2kgxD3Y9y+Wc=,tag:KF3eza5GxV79elh4HG7YUw==,type:str]
    SECRET_INT_INGRESS_LB_IP: ENC[AES256_GCM,data:iGq8ozh/V75Hcw==,iv:2MfhQX/kx1v1G+oN84oTRNRDBiC7/fMYngyn7pUAKR8=,tag:V67poYhQkjOGtHI5Vx/RQg==,type:str]
    SECRET_CILIUM_INT_LB_CIDR: ENC[AES256_GCM,data:bfiAxd0+MRrDoHT/Mw==,iv:g+wZEyY7nYWqoexC/1mrKDFguFp+hcJyAbKtB8Z08bI=,tag:z/lXNYXUIsdoLBdDx5f1TA==,type:str]
    SECRET_CILIUM_EXT_LB_CIDR: ENC[AES256_GCM,data:EfxP5v5uTdU/88DElXznX60=,iv:W+QUJ/BWcDYb0V8vjquBxhAKnybBnYBur2tK9WUTFLo=,tag:IQwAvVxYSGunpt5woKOFEg==,type:str]
    #ENC[AES256_GCM,data:RY/xz21XlqGmCPU=,iv:Plauac2MnZOLcFt1WetCnfwudURRu6qiLNBvYJu1JNg=,tag:o88WT1A3evjVL/0J3CPVlQ==,type:comment]
    SECRET_CF_ZONE_ID: ENC[AES256_GCM,data:xXCaz0PkhaReFw2lLVlxm5QLSqBmnEllWWZ0Z4OSJ44=,iv:et/GMCDULk2IoAGdL56aQZSziGyoIzxmUOjHPLuowow=,tag:nGEkhMNr2zi2Ang7ptQyNw==,type:str]
    #ENC[AES256_GCM,data:NvLdSw==,iv:FmxvZJTQWt1rQufXyIuJVzAfkiLN/BLfEb1ffRWtJtg=,tag:3zPiUUe+LeaNs3OIN0yIGQ==,type:comment]
    SECRET_LAN_ROOK_IP_CIDR: ENC[AES256_GCM,data:s16XDXFcN8Oc52Q=,iv:bgL4j/Zjp8VPCehStOcGf2QTXGdaq6vaRKWgb0BE+6k=,tag:rss6HQKelHG3b28tpSgPQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByam9UMjJSV1YrazF2WFhK
            czRHdjJud0IwT1pkOUR4TERBd3hiR1Q1U1I0Cm1rZUpROGc2Zk1pVUVLaHdjZDND
            bVdGLzgvS3E2WlFyMVdYNFJoTTRtaFkKLS0tIHZZeGk0T21lY3VzRVJ2NFpwTXZV
            dFQydjlMeWJkK0xYa2hVVXoxNTBWTGMKjUIGKZ5IYxZJ5dhSl3DKOk7hUJYZOO7i
            jgHUNSpuOIJ5rxUW2JulXx/JRkolgMOdDIZUwDj9iqcvGU80S4Yyxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T17:46:02Z"
    mac: ENC[AES256_GCM,data:ZjnWzAqnspwA/H1IxEo4zrWIVWloDEytDfp/IJNNgR7x67BoHi8jfG2sY6kmnAkhqaXXzmrbH9FbrqkGB+7UboOeNCVmktI343hNMyI2iZz3zqZGQ5EeCHhWKnZMDE+xLanUeeIR9yTnq+CviYn7YLlMcaNGe6L83VbibeIYQnQ=,iv:PJ5tQSbU2ot8sg26jOuOWo3k0ZqEN+hoywZrwNsGy2A=,tag:x2jYf18D0JQy8b5OY2/C6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
