apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: null
    #ENC[AES256_GCM,data:M/fC8vS5ou0=,iv:sKfIQwygzGzxwJoyxCyGANFaHYDcFOvObTiaf7lEY3U=,tag:TOV2weDhdFuv1/v64OkxxQ==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:U3hrdP7bjaknw46nZA==,iv:HXiuPDgLPz4nAMOvVzVYE52c5MeVf6RDxGxclz067Ak=,tag:sDEYjnyFGRPy3tABGOJUZw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:NMlpLvtzg4y/sQaf6eLV28HClecQeYNqHg==,iv:W3n+E6dKkzIT0VjKthSq+wPqYTW/H9onVwzPgeFURto=,tag:cdHWqe520mJogT/0PtRJzQ==,type:str]
    #ENC[AES256_GCM,data:UEiGSw==,iv:SARNrdO0slZayNN65g3Ta4xslC3+uPg52Dmi3L6lnGw=,tag:PidMG3izwITu8bN1pRbK4A==,type:comment]
    SECRET_LAN_ROOK_IP_CIDR: ENC[AES256_GCM,data:885ErBSBpGsi02M=,iv:TZICSRTWUu52W0/QrYUyStXCWQt3TZiHHhbt+rGTRKg=,tag:ULEnWLx3zLRaLP7a4gnGtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndGN5SVV2cTJYZ1RIcHhq
            WnB3TmFNOGs5Wk1QWXMzMkVpTDZXeWswblI0CkFrMytmL0s1ZU1TWGtCZW4xVGx6
            YXBOT1I2MCs3cTFRaUFRUFRRM0ZPL0kKLS0tIENlNzlvMi85YVZQQUNmbEtWazJV
            VWFkTTdYeDlTUjhvMWc2cDdwRkh3OHcKrovIBLG2XGfOYHkh85Xby5VLhTLxQmgj
            i9bp+evOBlNa3B74JaCuhcyhNrMpWIy5WrvhEg4uvdPebGo0m1SWZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T15:57:44Z"
    mac: ENC[AES256_GCM,data:WB9MGhlq3HB5xz+oC95Uz6ZSzr42SjxpYQc6DhxaSxAHar8VMtp5swby7IDhYL4xf7t9sU41kNUGVj5eADWsIsx87bZA90kCkbRIktLazqRk2r1CsJVm+uMJ/W7NLKScWRiYYKGZ21PA3EDS7YleCrlINzwDmIBdKszO++1CGTA=,iv:MHWmIfTidU+Q9U2lYvnegc6QmRZqUMrrTohmgEqq2F8=,tag:xOmElk6sAeDF+3Ghf13f2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
