apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: null
    #ENC[AES256_GCM,data:Dx8ppIEjeOA=,iv:9kd5bYQSQpxRjBbnrX8iNjtDPmfV+2kiXLZNecv+Guk=,tag:6EKyBXx5i8/JYfztdEkxDA==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/ZyHKvU/uwTwY0H/2Q==,iv:o+a8hNJjZ6o4HX8et1HMZbkBEwK2TiVB06W/Lh58pi8=,tag:W6aR7GAQCI19aGgatdAkpA==,type:str]
    #ENC[AES256_GCM,data:o29wYRWUxQ==,iv:ghEDfLFWJbxdx5rUC4aOEGSjLNf9KVpfRxZkI5bXrXE=,tag:h3pVP5J22PuBJ7GMAquvaQ==,type:comment]
    SECRET_EXT_INGRESS_LB_IP: ENC[AES256_GCM,data:Cnl3oaTAOEKOWzu06OY=,iv:ZR/D8c31QCGAzsoa9flvZ1YPBULDHcmL6VBtmnvUIQA=,tag:FwJDjp/RgotL9n86xKb8nA==,type:str]
    SECRET_INT_INGRESS_LB_IP: ENC[AES256_GCM,data:V0VXi+JhvRD00w==,iv:LCWOxNzNpMhXuQU9/omc66DF0XMwPlKFzK/tfM5ZKOc=,tag:qpeirxH+V5rAiI+dy4npig==,type:str]
    SECRET_CILIUM_INT_LB_CIDR: ENC[AES256_GCM,data:44eALj8+im8Zv3HHRw==,iv:vqyCtm8OMGGI0qbRWtyph8IuoN1+5V12tGRbQbs//Ek=,tag:MddeCd1HpMLA5hqQOBj9FA==,type:str]
    SECRET_CILIUM_EXT_LB_CIDR: ENC[AES256_GCM,data:9V3SDrwOQsLjHQN+PsN9vxg=,iv:YltJeUN04N1RrRvi2GXTygeoGhhYxYMWwxwNI71MeO8=,tag:ZBvrNXyxJN3fd8evex2psw==,type:str]
    #ENC[AES256_GCM,data:RAxhFupLrIQUGUI=,iv:OFmBy3ef0bSMERRJbD5ndnGr+TXeh2g3scsCzgNKArU=,tag:Hpaj8vM+V6Fg7YlcpgCc5Q==,type:comment]
    SECRET_CF_ZONE_ID: ENC[AES256_GCM,data:QPrS6kXH4mzBlLS6py6h4inxXhnHNVzugGydokvISlM=,iv:pCPPqJglx4zp4119EPXaVhvRZi4LK6dGeKJnw3dNOwI=,tag:xmQ2g/cMXC/Z32JJZ7JoFg==,type:str]
    SECRET_EXTERNAL_DNS_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:WP+6DW0d7Pz9uNM4zozyvfNKbVY5aS58POS2AH+LGlzC8Wro+PtJEQ==,iv:Gm1b40d6smQm6Wlxgnf1Y+PLDbaiFBJQbb91OA1Dmn8=,tag:y6EX/9kt9wa6LzOLpDhmLw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DSn1v3Xvj5n+NT/8B8uRRSgJId8XgQcKfw==,iv:mGOzA7t1lyV+Z4H4WAu0T5SricDDL5RpMZ6//rwlRl0=,tag:kkQlI5xrub8QA260hRLQZA==,type:str]
    #ENC[AES256_GCM,data:txvnQg==,iv:hthTOzub5KUdH4z6tUUdX0yHk3cv1cGpd80iAWLcDEo=,tag:K04u3C2QeI3Qsc6tSTndEw==,type:comment]
    SECRET_LAN_ROOK_IP_CIDR: ENC[AES256_GCM,data:v/0fmfJVuIyuLOc=,iv:N3cL4e5HPmxW5wXgwh36xPUrKmqySr8wiKG7Jarfqog=,tag:vqs+LexrVD7mlUEInALPjA==,type:str]
    #ENC[AES256_GCM,data:d7JeCBaBJLgAFMjDUA==,iv:8vkLz3WhCPZEngzfWH/GBFhpgd2V49nZ0YY1/CodbQU=,tag:6/FSbhb+OWDbTy/yceEA6Q==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU3kwdHFyQXF5UG00U1RX
            OTFGQ3gwdjU1cisvN0ZWVXNxMEtEY3UvbVRJCkF3c29JUUZMaUlXQjY1T3VkQjhU
            UzJ0S1oyTVhOb2xkMGpXcHVBRDRVR3MKLS0tIDhwb285MHFMa0lJR3pIMkY2akxM
            dkdFR1kxV1BMc3I1cDdQNVFLRmZpWlEKCVaMDs3p0g607fiH+HhcFt34sx9YhDkJ
            7OpPrpMsSw0wt5mdMF+hthn6cWtChCgMKBMmUeMfTihXBx9HZT7YOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T18:12:31Z"
    mac: ENC[AES256_GCM,data:cTUuozbmMT1YSMTuw4gspzztsSW6b53D5wti5uWVm1U83WjA7Dls6KeZNltbsug7OQ/SM5qCLasmWcHecqYHW0cequeS5O658Eu0UEa3JArI2MCrkc6sn5/hc9mB5Egv5ygHtfYsAzyRSkQ9df72OkXoovN4/duFu3yrSPjjmAw=,iv:rgNpcc8XtNOkXaAmP3bEr19qN8iwmSSTeCKBOi14M58=,tag:lcKTQ9pmDPTORxUdLQH/KQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
