apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:NPlky6jLOB8=,iv:UL9chqpDZ7ZEzkzq5mjZv8PmMkwCNpSKvXjF6RKni3o=,tag:Tqx8dcGXaiWmFUH+qhyyTQ==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Aj0Bkeidv2wChldfoA==,iv:znMJKhKkGqkgGARt0p+Y1AYrhWyQWYJVIJNc3k+kBfU=,tag:GOBP+/5RDUKZGC1ukUkcyg==,type:str]
    #ENC[AES256_GCM,data:wKlgrwYCPg==,iv:y6pjrV73MJKN9MkWw8GACZf1PEcXP0mwpo6W23k4EIc=,tag:MH3lWLzUg3v9fRaBjZos0g==,type:comment]
    SECRET_EXT_INGRESS_LB_IP: ENC[AES256_GCM,data:cngrCysiaJa9SNfBFLU=,iv:6B+pBY4Sqxek5spA/KcAAxLwv5wEnZ4S1BtRzIPJ26M=,tag:VXdaolJR0N4mtwJTe9/Kbw==,type:str]
    SECRET_INT_INGRESS_LB_IP: ENC[AES256_GCM,data:GtmzYtST2wOgog==,iv:uzqe4+Bo8N+cUmY3vP/JdS3rnFc9xGTI+Xjz+ZKqaD0=,tag:+cr+CD9nZW//cdI0bP2TdA==,type:str]
    SECRET_CILIUM_INT_LB_CIDR: ENC[AES256_GCM,data:wX2g7zhzKOyyGEQvBA==,iv:acd5dabtHEv3QHNYadT2ZAnlrMONDE23lqeTkZSbRSI=,tag:HmlxuH/s5Ezh1SIv3+wvXg==,type:str]
    SECRET_CILIUM_EXT_LB_CIDR: ENC[AES256_GCM,data:awLEQus8XxLqg8YMPswE8DY=,iv:Kd+metq/cWbFMZvVJeQ+cKfAfJIKjOZKSqk+AuUI13E=,tag:gcIVlrBNonZXN6BhdcS5UQ==,type:str]
    #ENC[AES256_GCM,data:9OFvnTwt7J2se08=,iv:k7qergnVfc2H9RvBNMXmwnjra8DO0gNKKIJbhdoHgr8=,tag:5mmpFbU/41T6LRoBqfLQkQ==,type:comment]
    SECRET_CF_ZONE_ID: ENC[AES256_GCM,data:mc4arzxZ37vTCHIITQ0uZ+g26tRdwJwh2+9FHGoeKMI=,iv:qW/A2PfmO8nxE1V/8pJg2+vYdVpjd3HGV2NVWK7xTR4=,tag:p67eOpBFWks6KlNqi0jANA==,type:str]
    SECRET_EXTERNAL_DNS_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:zo74lKXWEAw3uCwNv6OpOZST1L78WvX/KU+e7jJpEQfvlg8fGER/ew==,iv:+Q5udLLfrL4/9PRRLWIVf2CpXGgSnczUMlCIE7mSFV4=,tag:2QvbFHTP9q4Xo5C5rZatBg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KTUVGnzwTpHqWy6ZzjyiwWfRwj3oyPb6uw==,iv:SlCDHBP5B4Nyu6PnDkmzbAKUKjYqDiZmrSlkufngJFQ=,tag:tG0KmVgnapZCY/1h7epL+Q==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:wSEWi1mP9VVkrzKgpALDNYnQFVcAGGDiKOw3XjFIFIs=,iv:g5SONHEHJOnynoQpuOin/gx6RCmUakBb3TvOeLpc/6I=,tag:atsDi1yQTZKvLZlgu4jgdQ==,type:str]
    #ENC[AES256_GCM,data:S/SvHA==,iv:8QEBNajUWSvl1fPTWumhzSHwQOWbNDXWYHU1ulN7FyA=,tag:cLqlElu0oeJzvVA4lHrnhw==,type:comment]
    SECRET_LAN_ROOK_IP_CIDR: ENC[AES256_GCM,data:Tg7BZinQx143G90=,iv:Eo9/5RZM7x+fJbl8T3kZwUjbTohEYTH9tQZor7uoBhI=,tag:UBF9QewirrUSW4/QY4i5nA==,type:str]
    #ENC[AES256_GCM,data:L5clY9skyMfd5Roc7cg=,iv:MdPle16pQzVdckJgjOc23+N1gfDs0wJLPXgM3dgBGWA=,tag:qvo6/58zpAxXcNoRbJn4VQ==,type:comment]
    SECRET_R2_S3_BUCKET: ENC[AES256_GCM,data:vTyp8i/VBlBaNyvTrDM=,iv:0uLXhoqOkerDgtPjxNSvuzS0HK2tT8xQcEZs/NgfuII=,tag:bOleowWbziy8K26gSho/sA==,type:str]
    #ENC[AES256_GCM,data:atUxqt+O,iv:krs2B9tzjCBs+s6hjiwrZJ6bB11YFq7tomjjUbwRnwI=,tag:DaTlCOOJ9dT8IpI91JWZGg==,type:comment]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:dMHegUxh1ld4yn28vEzaen8izSzyZox8yMzEFaj7XAhEtReyrKLD+khrDl4U4wx37GEw0McUit7yJTSNZ+dWzQhFubcWNH31UvCe130UyQ==,iv:RB4x95yB8AFkXbh3LrCVIjCZeaI4rqPUOxfz/RSNPpM=,tag:IuikkNpUG0cO3plcGTNkNA==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:0LlHX+5tV6smWOozbMmdDDaF7Lo7wZ4lyP22faORFvw=,iv:YIk9gaoPkZqpWMEdWIqraYbLx930zv25D8yqDCep6OU=,tag:mpC2yQ0JUlqhH1usd1OOnw==,type:str]
    LLDAP_LDAP_USER_EMAIL: ""
    LLDAP_LDAP_USER_PASS: ""
    LLDAP_SERVER_KEY_SEED: ""
    LLDAP_USER_DN: ENC[AES256_GCM,data:UwfFa9AoQuAJESd/AZtuLxotFw==,iv:KNoFOT2Sp0FSHgcZsnp6kyw5EK/6DIn0n+vnHiCxciY=,tag:W29X2H/wiaDKySsClrsrKw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DSuxunc=,iv:HKN5zxb87FQbye5o3W4peSDmluJD4dtDrbq/xwBLmAc=,tag:eCw7PxBbzM7hU4X5IzOc6w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:nCRtvh5R7AEFlpA2RTApnEgWETAJZBC6uBSqd9MTsh4jWwc1tlT/,iv:TeJyStCcjNHb+JVOcrI3QZdhdFWjoq4cLRdKeQI0B3c=,tag:egJKnNQjJXxpjzR2+fMrwA==,type:str]
    INIT_POSTGRES_USER: ""
    INIT_POSTGRES_PASS: ""
    INIT_POSTGRES_SUPER_PASS: ""
    #ENC[AES256_GCM,data:lTqmZ+6ZGXIz5Q==,iv:C9oM8tAZcaCyFV4c3F27ozxhGVqQT5VcTYRHQuP4kmY=,tag:Rpk3kDpYPUfZdfe+meNorA==,type:comment]
    SECRET_TAILNET_PUBLIC_PORT: ENC[AES256_GCM,data:vuysOOQ=,iv:p9kDQbzHRRpemFVv+6I7oe4T9welmfy4/HwBsgZAX7A=,tag:iOUkZ0qL1qpCD7G+J/aqpA==,type:int]
    SECRET_TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:WXfOcJrFTgIL/vVTa5otLFdNzIgZlBD1Z2Wqr72KBT1xj4d/tSd2rle79+pswSdkNppSuiPJ0c0VV9dLLt/J+QI2jHniFhieRBSbug==,iv:XGPA64O8BOLfKFpeGfJENbuXPvfi+2RJYBN3eC7uB0g=,tag:yc4KdwADRC0Kc5s038CG9w==,type:str]
    SECRET_TAILSCALE_LB_IP: ENC[AES256_GCM,data:pZdyJRPZyY86HQ==,iv:XJyXcQkGl9ccY2kgzPIkj8d8k9TMoiP3VmxXt7VTvpA=,tag:mJsGltCUYpEPYW5l5CboKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcUFveTZnS2cwTEtzTlpP
            blRyZmp0WEJCVXhUSGRmVTdBL0FPTVdpRlNzCkJhZUIrZDlXcnFJMWMvbmNqdlJ4
            RFNsOW4vcEFqb1NnWmlvZmVhZVUvYzAKLS0tIEUyOXVNTEE0SlFIbGx1bVhrRENP
            WXNyN2thYVdVanM5eHl1WExReHJKT2sKyH4bPG5j64WN4xsNB0dnqccc62GtB6ca
            aSVBFTt/Ohw/tKoW6PinDlxlVPhjjDDTRjh9ujls30vF/LqqqhBzow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T17:49:32Z"
    mac: ENC[AES256_GCM,data:29zoWhFuojBA8LFcvmF4PYcfBHhs2knpghO231NuWNBVyxMG/uONZoZc+MNE8jUdIJvrwSq78EQGc5Gf/oyB8tNSRsvn7Xw5jdyQ2N3esNFvr88D4zS+Ox51y0jpb9lfUtN5s3aK1UXWomRCawxJ77k/DFqTB1VMtT5q5ERAMk0=,iv:lxLWeTKB9iy6+jNXSVRKa0B7lm2evWVhKC78mDKG1iU=,tag:SJXr1wUGOVBw9kkDq+bPIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
