apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: null
    #ENC[AES256_GCM,data:BvRNPf/7hSI=,iv:+xzHBx2hpzOnhp2Kkn8WUrQmB2OX6glSapDlza9+6yg=,tag:KiS/zpz65oY1h5hD44yjTQ==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:F0vBIi16BRXe3GmaMQ==,iv:eCOodWOP4SBSdJQOxWPQwdAxZY8gE0TgXbu5m68iAoA=,tag:fe2IZtKg98pdPyseUAE+WA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DgAqFvxq0X3v+qkSrWr2NlwKYbK3iVSUoQ==,iv:61T8Z2tVlsXtQi059izdHxOWZf1p0LGxcb3Hsb8sezA=,tag:2oFuA7kXnVaTLE5BSueg5Q==,type:str]
    #ENC[AES256_GCM,data:yr0qK3nlGQ==,iv:6I5DSp8yJTb4S2iW6j0jsoSY3LTd4xW9uxRcSQM11ZM=,tag:fXWRnkzjOy2ZC96I1pvaWA==,type:comment]
    SECRET_EXT_INGRESS_LB_IP: ENC[AES256_GCM,data:tfMwPAAPqvZUlw==,iv:le+xf7HaXYtlPtKyH+Pxrt+4YaVl9xe1Rza/m3fXyKw=,tag:y4GTyCG9o9Dy+7eCxnMauQ==,type:str]
    SECRET_INT_INGRESS_LB_IP: ENC[AES256_GCM,data:q+Omm9q2+DJZeQ==,iv:Ki/vZ/mJypBHkhJfAhxFqbgmn+FBij2GzSrBa9cXcmk=,tag:EmR3Yi8ZqswZk4w2l33K9g==,type:str]
    SECRET_CILIUM_INT_LB_CIDR: ENC[AES256_GCM,data:nzCkkQShVCyimHLxtg==,iv:yRy50U7DQTtpAQIBBG/5RGmQ/eG7oePNPX5KwFlr4Rw=,tag:bTQ3cLi1ZrrvlUUGXrUBsg==,type:str]
    SECRET_CILIUM_EXT_LB_CIDR: ENC[AES256_GCM,data:L+9xPpr+un2QrNSYVwqdIys=,iv:OmR0cOkpT4wubwqQoXtuhn6R/mA8Mgv/5GJIa4hUnyA=,tag:o5zNz5JsRoKLkOI71YgCqA==,type:str]
    #ENC[AES256_GCM,data:+yx+tCNTUB1TCbo=,iv:pL9GYPohiMf3MyvUxezNUqvhMIGzH99fWVgZWXTpv9Y=,tag:6gFsnIWQS9jwYpJv9oQSgg==,type:comment]
    SECRET_CF_ZONE_ID: ENC[AES256_GCM,data:JveTMn7U2x5IBRIMQBzcN6M3iQ0TdEM9hUMHrRFDNnQ=,iv:0HjIKMbvdrVMyZdEiYbHPeXhwxph515MF/2za4irgh8=,tag:zgY/hBOQPRhdIdwMCE0gnA==,type:str]
    #ENC[AES256_GCM,data:ha5NGQ==,iv:Axz8joUCUfUachNIRXrrLyff2fpkZ36BxJfBiJz2Vtg=,tag:/h1d56mMawUfAMSfBmlhZg==,type:comment]
    SECRET_LAN_ROOK_IP_CIDR: ENC[AES256_GCM,data:Nkyy82YLzLEUAOPKrA==,iv:WmAb4Hmx/qG+q7RSqv7HnXK2GkHtBMKsJC9m0IDpkcw=,tag:TwSBXyM8OlDR7O6JZbQRyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeklCUDJWaDlKQkhkZ2Ji
            dEZYaFFVMi9YdFVEUVRRWG9EVWRIOTFSNERnCnFLK0I5aTNDUlBVaFRkbGlEQ0g1
            T1BrVkRFOE9ZeTFIM3R0RjhhcFIzdGcKLS0tIFR2N21uaUtJYUZ6eWFvejNTcEU5
            Njk0Q0pjY0t0Nkc0OHZ5Z2h5THljaVEKO1GblMf6Z4BXqPbecU63iiDJW/IkWKW8
            hp02yD/XY2xDe1gG7vOrkR4nTF7umdQJA+E4r6oXOoUrzDbJ0ekjwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T14:34:32Z"
    mac: ENC[AES256_GCM,data:4iFQgHlCTzxz1I5OvP/cB1H9I/k2w/7MwxT8RtnR6oMBUQ37J9u2zhjdtCUlR3UZUczEBxf1v2TjuICWUoIUV/fHiSroF2ME7vCFi8jN9h5MUFtITDcjU4+9mUfj6rdfQLc64rpoF8KOEcUudd/YfjSrGtL1YM+q4KWVQuiFco0=,iv:Q1SC9oWvgJFoMDIPdryK7fPo4sCeM/cXU/ybITLaSr8=,tag:FB1mJvdzmSvoWvzJgS5WKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
