apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_ACCOUNT_ID: null
    #ENC[AES256_GCM,data:T37mTSAFPD8=,iv:/2OvZbkevvu1RXkHMmHv+9NJ13XWGTvwixNxHFHc46M=,tag:F7oxeAO6ejjLEi0PF8rQHQ==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ho3vAS+7mJLTvEsO/w==,iv:FZtIQ3cuNkFX5rNvwOMs9mDacZdl9bCVqDwjZioglzg=,tag:/jTgQnKZa+1ycSqzbvXFSg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:LvCr1SPRDIRrdzwuQYkuNpjFDkAMBeXagw==,iv:wbGawKQ0NqhpwQNqhQ6jLiYCuhBJtWpRkr5G+Ygspao=,tag:Tyio4oIg1r2/IXYG7VF+0g==,type:str]
    #ENC[AES256_GCM,data:uTGP2A==,iv:dLBUBJ09E5KLtYf5IlfEvNXG4ktcK7UzTi2trdIMwko=,tag:C7AaQYCLYJ8XuTTJdHUarw==,type:comment]
    SECRET_LAN_ROOK_IP_CIDR: ENC[AES256_GCM,data:dUi9muDjNtdgvos=,iv:tNX9bCIbkPP1ih9EgiMqSWADUVkVX4jvBUPSXSWHJQw=,tag:4sTyZfdUjOt6wgFQg1zYAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdnpNR0RoR2JVNEdiUTUw
            dkl1cnlyOE1DRTMvT0tOWTdNNk9KZkI5dmhnCldBRlZiVFlDTFY2eHR4bDNrbnpB
            bmt0ZFVoS1JoaUZLNC9BVnQzcG0rSVkKLS0tIGdpQkJaK0NqSU5KaFgvbzFYSDZK
            OTErK1F2M3J0QUJlTjhTeW1FZXhsaFEKUvgSspB0pWBjE3nrJHSH7DQPPF23dCS5
            2N/2W2im7bQaODkCJl30HDWcflM9cR0dYgyh9mMLyx619o/OADny0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T04:08:18Z"
    mac: ENC[AES256_GCM,data:S6/u3qeRAMAjs6S4Y5TdzEN6ZqQbA6+vY9WX+dAfL3Q/cFl+ZzNE0K1f4FDqtDTSHPUaMRY9ZKSlZARPU3+FgaklTpwRcICrHYSwzBAX5nKIVButzhjtGpsdOougq4meCFJq6eQvWHisripH112AWJS9809Q2bzrsnKKWO+m/Yc=,iv:MJ1r6VZnqUvqdAx6LbSOcoZLnUX4E3JlZMYJjlEdL1M=,tag:6fMoOnP9R/M9s3/8PrgZJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
