---
alerting:
  iscord:
    webhook-url: $${GATUS_DISCORD_WEBHOOK}
    default-alert:
      description: healthcheck failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 5

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

storage:
  type: postgres
  path: postgres://$${GATUS_INIT_POSTGRES_USER}:$${GATUS_INIT_POSTGRES_PASS}@$${GATUS_INIT_POSTGRES_RW_HOST}:5432/$${GATUS_INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

ui:
  title: Status | Gatus
  header: Status

web:
  port: $${GATUS_CUSTOM_WEB_PORT}
