---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: ${CLUSTER_STORAGE_BLOCK}
