# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: plex-restic-secret
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:DlRUiBn2GF5dwsJEJjalWtdXKuIbuGMB1rWbzc3xoOTaK9C0W0B+d8O6SwYsE2LRWB4HpcsdT8GHukzWHNjMfrCTgTBlJU0ZayYjVf0AVkviLoFQuXBl47D0,iv:Wd4hJpC89dQhb2ITkl8Hz/0VAwBKnKpj7wwzw7bje+E=,tag:Yig6NmMkO/VdpmXaAS0N3Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:eULVE6ZerW+raNhUjA==,iv:QNq8/u5EHRwTl5mYJVj7SKEGjaVBTKhy0/Ma59wmNYE=,tag:ufTfvGGBekkeOFZLqrsHKQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8ZuZsXZYC3kefKkHNGfqZggmMdnhBE+ir3nBVKOrNeM=,iv:ibIh6fyP7DpwaQmdsEK+4WX7UaSN2CUeTOXlMrpSLWs=,tag:Tofw+Q+Y+HF4X7yX4kX/9g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VgiUW/hinA6VPND6x9lGnU1sXRpfpTIe4e5nOypkw7Pjop2jJV0YiDV4qQaUOBcJgtUYCTjgxIh4a2zWkS6oKQ==,iv:Q/rmvt4OuJ8TNx8ATuPhBkGx/us2nGz+7xwMnnzqrJU=,tag:LEmlWH3Yyw0HBJjCvgl2Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWTVZSWxOTzhBaVB0T1RM
            SVpMNlYrVy9YREdwT3pwL3FnWG5COU5JYURRCnJObHhVcUIyN2JqVkJMbkVYMG9z
            S1BiQkJMdVBzVGVoSHQ3ZFFtNEZJYncKLS0tIGNiTGxKMVIrYysrdDYxbk5qVWJY
            eVRwcm1CQmYvUW1ZSTZQcHE2VmUzTjgKI7HJocBQa51bC9Xv4ySMd9zpvv8+vK9Q
            G2BKGKv+z7hCijgCUO9URc9P9yOie5W5Lq+PQN5k5B5cZ3g1yO4zYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T20:00:01Z"
    mac: ENC[AES256_GCM,data:z6IwFc9dQwUh4kxLKToEbZpnF67Xpre1K4Aa2b554urnVzYXURDPDRNgSy4OKmf5PDrTgoObR2/U4k4lWYrJsUP9BJIfQoAhd9n1HmGgQpIKHhxdhLz4Z+V1Xs0u648ONAI8k6Ltn2fYn4bqKN5va+w0fLDqhTrbFbrwtQtV4xM=,iv:DcIeghD4SJ6jQiHvfZaHpAfH3fhY4/kcIpBP6thBBFQ=,tag:eQemv/rZXEcFqQLXRiAQ2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
