apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: networking
stringData:
    client_id: ENC[AES256_GCM,data:Eu5kh2l1VN8gwXIz,iv:mc+vUuhDEKlqCaGJjFh1sXz2GmHCp027ilGlkD0S7gY=,tag:wDFEDeDsDEj0MXXtTWXsBA==,type:str]
    client_secret: ENC[AES256_GCM,data:++lSqfHOqhxry3ThUkLW0wPGapkbXzpba0x6G7J0ab/heF65OfFGrmRnyGqR/CJwruv0gYWtEm7YIQ==,iv:8K+lLr++vkiMDiAB+mN4bv+H2XW6mGG5G3eGPCX1Khc=,tag:VbkgPWM1UerN/V0jejfgAg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QVRIMVZvQW5VSzRxNUY1
            ZGZjVDJnSDZjVzYwekM3S0JEcHBtSjFTd0M4Ci8wbldMYkk5V0JoWWJOcVpsRnZz
            Y2pEN3RkWGx6dG1XbFBubGpHQXMwK3cKLS0tIFEyUXByUjZaQXlteHlMeW1LRGkv
            YitNc0tIazNDY3ZJMGxWMHE2QklFZ2sKW9YBEtbsMPO/rLUtb+YA/aQ1wYROAKL2
            EySHFmU8WgH9vOw/pE3qnkCH1L9KPx2EG4YkJcJdNhzVnwhLbpv/Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T01:33:18Z"
    mac: ENC[AES256_GCM,data:8UHoUY86uXiGmMX60ylbM8AN7wM8ACokJHysD9t/aZBTVfiFfCe15T/WUCnoSk+02MNRo/tQGRj80Bo9cCQHd0cLkutJNMf4YmpmdQUYfkbGBHBnAWQX4cmtuyHJGlAnSjWPRYT+viJ5AW4ECZlnPrCy943MfIa+Sl4O11VXIkc=,iv:0Ojs9Pgsr83ctSM+evTD1nRU2hAgyBXA4osFOBCYi9w=,tag:nb60mTbfBtgQJjmKKuMzxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
