---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.56.1
      sourceRef:
        kind: HelmRepository
        name: tailscale-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # values:
  #   operatorConfig:
  #     image:
  #       repo: ghcr.io/tailscale/k8s-operator
  #       tag: 1.56.1
  #       digest: "sha256:bb02d69bcaa11d96d9a60bd5a068172e0a137dd8b5df994e00e6b27fd451bf28"
  #     logging: "debug"
  #   proxyConfig:
  #     image:
  #       repo: ghcr.io/tailscale/tailscale
  #       tag: 1.56.1
  #       digest: "sha256:ac0c192f6cba52877e4d9c2fe8943f16c0ab44927605a21416852590e3ccb71e"
  #   apiServerProxyConfig:
  #     mode: "true"

  # values:
  #   apiServerProxyConfig:
  #     mode: "true"
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: operator
#   namespace: networking
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: operator
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: operator
#     spec:
#       containers:
#         - env:
#             - name: OPERATOR_INITIAL_TAGS
#               value: tag:k8s-operator
#             - name: OPERATOR_HOSTNAME
#               value: tailscale-operator
#             - name: OPERATOR_SECRET
#               value: operator
#             - name: OPERATOR_LOGGING
#               value: info
#             - name: OPERATOR_NAMESPACE
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.namespace
#             - name: CLIENT_ID_FILE
#               value: /oauth/client_id
#             - name: CLIENT_SECRET_FILE
#               value: /oauth/client_secret
#             - name: PROXY_IMAGE
#               value: tailscale/tailscale:unstable
#             - name: PROXY_TAGS
#               value: tag:k8s
#             - name: APISERVER_PROXY
#               value: "false"
#             - name: PROXY_FIREWALL_MODE
#               value: auto
#           image: tailscale/k8s-operator:unstable
#           imagePullPolicy: Always
#           name: operator
#           volumeMounts:
#             - mountPath: /oauth
#               name: oauth
#               readOnly: true
#       nodeSelector:
#         kubernetes.io/os: linux
#       serviceAccountName: operator
#       volumes:
#         - name: oauth
#           secret:
#             secretName: operator-oauth
