apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: networking
stringData:
    client_id: ENC[AES256_GCM,data:NTIRMRWg+QZO3u3R,iv:ktCUVtUxHhEcU0TBsDTAWZhyR350tIPokz1hET+jrPc=,tag:8FaamtP9nvaM2jLJEMKHZg==,type:str]
    client_secret: ENC[AES256_GCM,data:dye/Dc4I2O6+QgXhyVkUTVZYvPkurl7GZY5vw9gc8JPf9xgKTiZj6phrZkLGv6jyLdRbYSM4Q/308rRRkPXEtaJHgqNt6uMzMYEHbbU=,iv:2VWROclDcC5VuChpXKwMKHJrsdMGX8FwO+4kiA9YM7U=,tag:gMGgGfvPqYgP1tUe0Bbktw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeWRHSDBzVkVYVnh2WUxE
            ckVEd3ozYWtXcjZ6WVkxSXFIMjNOd2FjaVM4CkJVMkZJaDdoZktYZXYzaEppaW01
            dExLbjQ2dGo0bmswNWh0c3pwZkRkdFEKLS0tIDlEVHgwOVRBaUZjd3Y1TklsT1Vz
            NllmRk4xMDU3R1FDaHZUdGgxK05IMXcKHT7/wU0BLJzAEH3baKBBktjFwaAqEfGr
            qmZ7FRCP/lKHcmjX24GYe76FuMf8M2DUmiQ9PvpsP0PruTF3lE41Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T18:32:48Z"
    mac: ENC[AES256_GCM,data:EC7NEa+XPKAIb1HIdllVIhQNUgWPH3X8COfrIS5FRKALh9P/jqPxUO/5fEfC/w4KgvxVIAkhRpuHfVggdhtXOFL+Ek98zbwgH/hSIR2Vxv61szeYiqlSExomU9mJiXFPY5FpYKmNC+FrP4GXLZSpwi/Dl4mzIuw6YyJ6C6PH5mY=,iv:CLRavP8fzUVyHxK5vrEvh2XMpRwQpXe8FOi4QuTRMvA=,tag:rvgSNKprlBjKAHWQemQNVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
