apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        kyverno.io/exclude: "true"
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GalX4O+tsIfwIHScYvrjwvG4TSJC+StSUxCxViiq0gE=,iv:T4SGOuAqdZq9v8FBgfxrXvPwR8hi3TGg5QQWrTI7qII=,tag:sMK2hNIe+2BYkgoSIBZc3Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dDQR0izzStudUBzfTY4n5ao2kJ1ATX5QCiuFJDXy1ftEsqe+KBEzB3L+9QiGs4C/0gUoB7ClGQ2XkOGgZPiWVQ==,iv:dS/ozm1TP8z0sa0oHOP8m8csNS+Ew6fbpCsTjkWoiSI=,tag:3fASdoTg1EO3qcCZtcDYUw==,type:str]
    username: ENC[AES256_GCM,data:4PjCQejAgLM=,iv:emvCtHcX3j77YFviDRw+/3sMaDw5NIQbhwQyCE6cBzs=,tag:ByO5U5CDuZ3r+bJE3rFiPg==,type:str]
    password: ENC[AES256_GCM,data:jDmH4t+nzKk=,iv:h2N7CAajmwkhJ5afSbBsS/idF6n5q6z3TifK3jQUXVg=,tag:Ny/vaww3MDVAjpQ+L8zVqw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dEZGZUF5OEwwZVpDOVBE
            eHNnM2RKQldnUS9sY1I3anVPNi9tZ0p3OUJZCmlQNFI4Tmp3WjJzNWNtRG1nUmNU
            bTVHZUk2Wkc5UzYyWWVNRGFJRWJqdUEKLS0tIExnMElVUHdwRDR2NmhOakhtZE9v
            QUtXdUN3YWwyTkFUS01EcHpTQ0MzWmsKsIoPhDOoFnRoIHaqxdLyXhMTd9hx4jkT
            BOlJeFTFGdSmcTGfsnU0mTzEq3WtQHUIx4glnQQoeZXdYrdPA96Fvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T17:04:48Z"
    mac: ENC[AES256_GCM,data:0rINg8XH5BBASm6pKqOxdrGw+/P7TigUhGi6ot5m6VtWpVnYpd3/XA8+0YVUy93UACj4mIp+xgaeClv+yM8iPmEdgjaNKjFT1VbXAoh8oGvnMLxKUyf1rUQrDdp6O5gtArnUilGyb27oU2NSgxXETaH6S37oQ75KA5dckVO7P0k=,iv:DEydFjLd0UJI5WIlTDOeafNgvu+1QWjEv49/LprKNY0=,tag:iLd/Msf8hKuvGUmmpktsBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
