apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        kyverno.io/exclude: "true"
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:n3SQSw5zZ0WPn50fvKXKg6oUW/VX3pEsPC6dINQmVzml,iv:LQI721NezB1i5t/idJxaKhn94XAxRsWJdR3dQCq3hQM=,tag:4kWPmrlU1DHLrjs/mNlGeQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2cBEuUyp0K95gw0kzKyZRJLK4Ww+AVWT+hUQhI9DtF9jSUu/8etMNmRv8q+lgEUveEzgy40GMfoOhlOjNUBIKg==,iv:DGImJyePZ+dbx3NWBYj1X4bROGeqFIlI7IlH/6gWu30=,tag:5VANToPp+5kGZ7ey9EM8Hw==,type:str]
    username: ENC[AES256_GCM,data:jSafDKxU0y0=,iv:bExM/ahY2R0W5w/568AhtoIUdOA0W+my+TU22XMtoIE=,tag:Y/jdlUtGc3iew3b03VCE6g==,type:str]
    password: ENC[AES256_GCM,data:L3tmga/jBAQ=,iv:BVpqKQoGlU+vTilltGXV9Lr1fminHuOKrWoNm5ZIX7M=,tag:ro4obM/vtTBoNFXUiuqOGw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dUNNRFU2eDc0bEVmSWhp
            dHAyNDN5WlBhODlhVlJyOHBvOTFyRVRhc0MwCmk2dHNWU2tKNjNWUEdaUFkrZVMy
            M2pJTFRENGxNclVHb04raGJmNmUyKzQKLS0tIEJRYXZuajI1UHdmNUM0UUNxbEZI
            cDh3UWwxRU5OL29Pc2QrYXhiSGJDYkkKhdW7LiTZfHbLUFI4PQU6MgfeFAj4zOcz
            1MvNj/76rFCZIEqTxoA8HjrVnuXDvmWDOcmv4LHBKgvNwVTb2snRSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T02:36:03Z"
    mac: ENC[AES256_GCM,data:SDIRUk5Vs/GRILGcQx0SZw96FoGMWCNZrv4FibQgub266yPDpztTSbDpnRB8/8mH83aiVPgMqgVfw4t61jBYmMj/i0Yb64QeEv55b3blRKzQkZW97DeYiFd9V52zk+xQfUSWbr53Pk/6h8TQPM++7P0jlKUEKtv71LaqpO5QfPw=,iv:IDvacyLFE2zKtwgfx9SbzIB5kEQExpzIQvhUyYKc6wA=,tag:S7Ay/QH18jzsTIGSCcn94w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
