# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudnative-pg-secret
    namespace: databases
stringData:
    #ENC[AES256_GCM,data:SMs6ZFTMzMaqOu58Qu89Qlj6uLRpSBcV74w=,iv:7QAZ8gwRkcjUtWC6WKrSw4j82/bAWLBgJJ+rdWFfmJw=,tag:9eX6a2PLiG01Y+p1bd690A==,type:comment]
    R2_S3_BUCKET: ENC[AES256_GCM,data:IdGyurn69pwCl8IhJruzyAo+ibI=,iv:IUIdqHGb7cJy08coz2KooTsAtdDE9/n38DMPNed/lSw=,tag:hKEV3GM3QQQHBLHH4yAO6Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:BTR7RrcmS73mUVCWzZcO+T2TYHMGD6Tqtu2WBPSQ64A=,iv:P+X1f6tsv+BFXckysTe3bBWLuRxyk33+j+wUXdEZaSk=,tag:QuFRB2V5vMT/z6rC/UOxeg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RpJ+QrGaviGzurp66MPClbDfhdrZ7h1JVPE6drQU8jfcow1bB0KmkmuaP0ctwqbVTiKO0J01QHUiBBGjzOdWOg==,iv:hTMbxk7Hq1i+306UKOZibBnuDAib7QfSU/cE7jOzWdw=,tag:5lkqVXUg/mfjYlTE2LQ0yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydHowdVQvb0xidGhHeHBM
            SVVNV2hOelhQRTNhVzl4ZGh5eG9nNFJMcjJVCkR2YkZvd0haYU83RzVtaGFvSnl0
            cTRrU0pZL3dLSTBIWDVuM1FhT0pXMGcKLS0tIHRMeTJWVEo5QVZOVEVTdXpZUFdS
            UVZIR0dibjFtVTlydGtnV09odTJyOWMKKxa61cZAZVW5dNzmlILeRMHTDXTJyH+t
            GwGcn2SlDK4PaF4dILUQO97/DZgkfXNMUMNMV7BHqdtEn+tnqmKX2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T23:19:40Z"
    mac: ENC[AES256_GCM,data:5cwI9GpHRco0390YmYbTVIYokGC+RqmRIZOeIeC1UGBLCLYVRwWPhNTuL9rJI2Fh+Pmdks0fWLrvfJVl/vEidF/Tk+PrivvA7QNl5dZvrvdKOcjQZfJtZnK5ZwvySKdqUWbo40yu2q1oeWDeri1+7f91ucjAMIeZZ2v8+hgsQno=,iv:wdC2fCt4t8CTeHWA8JlL8wntmKCE5rdoghFqJ+KW6/Q=,tag:CuG6YDUGPFvNRmNyQSxDiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
