---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tf-controller
  namespace: flux-system
spec:
  targetNamespace: flux-system
  path: ./kubernetes/apps/flux-system/tf-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tf-controller-terraforms
  namespace: flux-system
spec:
  targetNamespace: flux-system
  dependsOn:
    - name: cluster-apps-tf-controller
  path: ./kubernetes/apps/flux-system/tf-controller/terraforms
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
