# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: gatus-secret
    namespace: monitoring
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XT6/RB4=,iv:j013coUlsfDbCKIPJUoigZ/ZQ6BKkD/WzxvcQLGtj2M=,tag:ERqtPonyQ6zQyCVQjqSE8g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:5reD0NBOmsS+O3Ur1KK8BQlEj/f2omzwxyCU1fvtPS20Yt4Afsox,iv:U20l4EM6M6XHtEb9szeEhiDj7IzfLj+OlG5EJaC3NkY=,tag:IEZK5iFTUsjbXiDkuJ/1Ug==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:GP9kOZs=,iv:H8jZu9uXo/m55VHK4k4zuSDMimVwwHOqNUV8McU0sLY=,tag:lhsRGjs02RdKj+UtG7Sxgw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:lloxFYI=,iv:LneQu0VvWfg8Ek4bm8fd49tvYMhrV9cJcEiBIJvqkxc=,tag:UkxsHvKJ4xs9wVLlJKwhSA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:zm5NGR0rQVI=,iv:0zps3ZVxVV4aOQcdN9zKPmJarA2C5jOQwKpbhZznx4I=,tag:22XJcscfGNDJN3C6AJ/4sA==,type:str]
    GATUS_DISCORD_WEBHOOK: ENC[AES256_GCM,data:0ejzZGlVyvbCoGdQVTGFfQPukNkyvdz9Uz1FxPoK1wEYb/hMioHKgMXd2Q0D6r2j14TQg6uBuPScXUBsMG8cGJKHbUQGrFDuzZ6j/Gs4Ld/NCd37Um+i6JaneLjSt8dC3tqv340Vih3y2Nx1ZX8ThHoDEtiDSZzzKw==,iv:mCP/spB24Pj30jOVSxIkZekuePZ+ZD72U3oRAoW3M9c=,tag:zVVYAjogzt8bgQSUDvjZmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbkhUY3BnTldUWWlUYldr
            MXlyUzhOZEI2ekhXNXNZeW1mU08wSktkUHlFCktGbkdqbkRhNXJLWjN6emNGeGNS
            VWdtOU4vWWpOdUJkdTk0NU40U21PUmsKLS0tIGM0TS9OOE9waHp6YTh3WFM4eHhK
            c29LRk5hdkxHLzBIVXdENndKTHAvRVUKtyc90Ts9v/t0gHiq1zFecpx2Z1eq/w0C
            toB6XHGmjQIcyn8/Uay7v3vclj3MpUFy/2Yp97UBK4u9lMmwymAxyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T18:23:25Z"
    mac: ENC[AES256_GCM,data:2vumOm/uIFAiON3z15OaxMU8tBM1hnmd7t0/sYt9l4BMAMIkm3kwU39s14Ru+HosSscslxGw1hViGWGnyBVr6oT4w7vzNR5zITDDgpIL1xUdeJsrMAOUcAEGSYfUQhlT75HbxopfEE2yqT+15pJfwbxLpQqWqVFldcguopay8ko=,iv:0kP4YpxG7ZuiYDbuAJliNUeK2UkHJBYT/16F8h+2pmI=,tag:oHd/Y8qySL7azhgZHYa3vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
