---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: lldap-secret
        containers:
          main:
            image:
              # TODO: Move to semver when v0.5.0+ is released
              repository: ghcr.io/lldap/lldap
              tag: latest-alpine-rootless@sha256:9640de3e67823faa5477c4cd499a0b3117c3eb0d189f02f0ea8635e0af26d6af
            env:
              TZ: ${TIMEZONE}
              LLDAP_HTTP_PORT: &httpPort 8080
              LLDAP_LDAP_PORT: &ldapPort 1389
              LLDAP_LDAP_BASE_DN: dc=home,dc=arpa
              LLDAP_HTTP_URL: https://{{ .Release.Name }}.${SECRET_DOMAIN}
              LLDAP_SMTP_OPTIONS__PORT: 2525
              LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: NONE
              LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
              LLDAP_SMTP_OPTIONS__FROM: LLDAP Admin <{{ .Release.Name }}@${SECRET_DOMAIN}>
              LLDAP_SMTP_OPTIONS__SERVER: smtp-relay.networking.svc.cluster.local
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:account-lock
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      tailscale:
        enabled: true
        ingressClassName: tailscale
        annotations:
          hajimari.io/icon: mdi:account-lock
          tailscale.com/expose: "true"
        hosts:
          - host: *app
            paths:
              - path: /
                service:
                  name: main
                  port: http
        # tls:
        #   - hosts:
        #       - *app
    persistence:
      data:
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: *httpPort
          ldap:
            port: *ldapPort
