# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lldap-secret
    namespace: security
stringData:
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:lx/WYagfLd15XR0Ui5Z0dUhyvG7jBSpFleljAt4GkYKY2DC4yl30umM4hy59IbqXeyuQ6fEJCndDl47BEh1eMD+F30ABJRWy3IA=,iv:rqcdcoYiJ6fPVmi8Iej3x2RcZXqOw4fM9N97w9LrEp0=,tag:YLBJoAaLErpZXYNTfWODyQ==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:ArjYrrzqKW1D+OtHEaLVhfzQF/JhpjO+/TepLn4M/po=,iv:UMAY9vQ5ZFuAGDZNo7Zj71mf68V9YkG7qxdorQBiOpU=,tag:f4bPpDAgPNrRHFROW/QqyA==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:xMvjHzZmyW+SaZKA03hfucoqIWeaWUyH0A==,iv:W4MREDHQkj6rIJg33/9/oo6dvDiRnwhiD0FhIRY1GBU=,tag:yOSyNQItWIa4KRLcVdLrvw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:bkps8Qw=,iv:gKvT8Nj26b8w9T8wiQjpdKVOXUKXPNF3xWl1QGo1Gs0=,tag:vxw3a1XvMd7zeAZudt9b4w==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:09saGCaeHWaZrqIwg3VcXROnak8f4Sv0eQt3/jo08s4=,iv:UvvvK2vOEDQEbn8LvkEzXW3IZlm3KJrXqCdMFYroESc=,tag:bkasCLTR5V3TmfxbE30V9w==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:tNHS9l8=,iv:hsyEEG2SifgKO/XfgVVi9DqS6fjfoqxCH4NnBT9TYUA=,tag:lv3pm5attLc3fUd/uV7Mvg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ycbVu5Y=,iv:U/ITba+iSYZDDuIvJfv2AwUljPLMgkzTsDg5Sbpjqd8=,tag:bf3sa2nBjKz6EsM9snczwg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:uOkQoiSkkK8EwrgGYNu7YRVYYGwrgV4EPiqv3tuw82AMBfT+wKGN,iv:6bl104L8372KaWnNqw12uPUIHsFdXUSnoUhCfrnojUg=,tag:6QpFqXTQdzON8ypsR0QSYw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:xLCr6rbxWD4=,iv:MMATCiyiFofqpo6hRJSC64VGkB1qLa9dryVLl++ZpnE=,tag:rAdyDHgsnFZUTJdKk/m0Qg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kkyQpsj/UFE=,iv:C07Bt3t8ktqZaKo1j6fhUABYcrUn4ek0YiL1ThTdfjU=,tag:pV0hf8cu9qLv1a/GF09eKw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:lbdeqfbZFANRJ/fQXsebOX35pEmu543Ko+0Pms6EAoXJ3RjMYG/fg0XvgB59RSr1zNBjPz6v1V4BhT/u9fkWlw==,iv:ToGdC+Cd0TMSDQL11YLmA8YqF16VqWgBSWsWn+/JdNg=,tag:cMseR2EWw6pYI6wHEmE7+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ms2d7n4yhaq0mdap4cfyaq2xtfutlachqapkjfr0z2qr7ghc2ckq000jhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQVo0UW9HNStCcXNoWUpK
            ZGI5cjlpV2licUFld1ZBRHl6K3ljWjN2ZzJvCjFzU2d6cG43bUxSdE1TcjFqendo
            eUVIOUtJbWtDNlJEM0RWYWpRZ0RIR2sKLS0tIEpxTHpwcTRxN2tGaDhkZUppeWE0
            TkJxclcwbTJWZERObTBTR252ajFiRFUKl8Q6H88+1KIj7jkrbu7wb3XzFzv76qRY
            ayyeugwnIUJIJzbRHwZQltLVy+hx2D+GSnftaM9qVhT9Knjs14hzDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T17:07:29Z"
    mac: ENC[AES256_GCM,data:XLvyHAwJbOQcW3i60GxgfvM/D5reh9/2Ar35/WgyOMy5pxA8VZt0trbbYJlRVe3v7UL8zt9h5745/HP+sFsaReQSZEgCzs7CN+SXYzkQ4QC6UiOTESj7LKX6fYflh7SaNYKRWyKQ1FzmTTOtYfkkIgeIzPH9N4JlL2HMKU4YRGE=,iv:FTPpRG4TKTx05bxwDN5+UbE3zlBfFCxsZxVw/hA/vT4=,tag:b+SYI5V/5y7TvufxKTFVvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
